// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PythonSucks.Data;

namespace PythonSucks.Data.Migrations
{
    [DbContext(typeof(PythonSucksDbContext))]
    [Migration("20181023160825_startup")]
    partial class startup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("PythonSucks.Model.Hater", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChildTrauma")
                        .IsRequired();

                    b.Property<DateTime?>("CreateDate")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Surname");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Hater");
                });

            modelBuilder.Entity("PythonSucks.Model.Reason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateDate")
                        .IsRequired();

                    b.Property<string>("Description");

                    b.Property<Guid>("HaterId");

                    b.Property<Guid?>("HaterId1");

                    b.Property<int>("RageLevel");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("HaterId");

                    b.HasIndex("HaterId1");

                    b.ToTable("Reason");
                });

            modelBuilder.Entity("PythonSucks.Model.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateDate")
                        .IsRequired();

                    b.Property<Guid>("HaterId");

                    b.Property<Guid>("ReasonId");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("HaterId");

                    b.HasIndex("ReasonId");

                    b.ToTable("Vote");
                });

            modelBuilder.Entity("PythonSucks.Model.Reason", b =>
                {
                    b.HasOne("PythonSucks.Model.Hater")
                        .WithMany("Reasons")
                        .HasForeignKey("HaterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PythonSucks.Model.Hater", "Hater")
                        .WithMany()
                        .HasForeignKey("HaterId1");
                });

            modelBuilder.Entity("PythonSucks.Model.Vote", b =>
                {
                    b.HasOne("PythonSucks.Model.Hater", "Hater")
                        .WithMany("Votes")
                        .HasForeignKey("HaterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PythonSucks.Model.Reason", "Reason")
                        .WithMany("Votes")
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
