run:
	python manage.py runserver 44346

makemigrations:
	python manage.py makemigrations

migrate:
	python manage.py migrate

createsuperuser:
	python manage.py createsuperuser

shell:
	python manage.py shell
