# Generated by Django 2.1.2 on 2018-10-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyapi', '0002_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reason',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='reason',
            unique_together={('hater', 'id')},
        ),
    ]
